version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # puerto para conexiones AMQP
      - "15672:15672" # puerto para interfaz web de RabbitMQ
    container_name: rabbitmq

  app:
    build: .
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    # Este comando puedes cambiarlo para usar send.py o receive.py
    command: python recieve.py
